import Kanto from './assets/kanto.png';
import Johto from './assets/johto.png';
import Hoenn from './assets/hoenn.png';
import Sinnoh from './assets/sinnoh.png';
import Teselia from './assets/teselia.png';
import Kalos from './assets/kalos.png';
import Alola from './assets/alola.png';
import Galar from './assets/galar.png';

import loadingArticuno from './assets/loadingArticuno.gif'
import loadingBulbasaur from './assets/loadingBulbasaur.gif'
import loadingCharizard from './assets/loadingCharizard.gif'
import loadingChicorita from './assets/loadingChicorita.gif'
import loadingDarkrai from './assets/loadingDarkrai.gif'
import loadingDialga from './assets/loadingDialga.gif'
import loadingGengar from './assets/loadingGengar.gif'
import loadingGrowlite from './assets/loadingGrowlite.gif'
import loadingGiratinaShiny from './assets/loadingGiratinaShiny.gif'
import loadingLeafeon from './assets/loadingLeafeon.gif'
import loadingMew from './assets/loadingMew.gif'
import loadingPikachu from './assets/loadingPikachu.gif'
import loadingPikachu2 from './assets/loadingPikachu2.gif'

export const imgs = [
	Kanto,
	Johto,
	Hoenn,
	Sinnoh,
	Teselia,
	Kalos,
	Alola,
	Galar,
];

export const gifImages = [
    loadingArticuno,
    loadingBulbasaur,
    loadingCharizard,
    loadingChicorita,
    loadingDarkrai,
    loadingDialga,
    loadingGengar,
    loadingGrowlite,
    loadingGiratinaShiny,
    loadingLeafeon,
    loadingMew,
    loadingPikachu,
    loadingPikachu2
];

export const questions = [
	/* Preguntas de KANTO */
    {
        id: 1,
        difficulty: 'Fácil',
        question: '¿Cuál es el primer Pokémon en la Pokédex Nacional?',
        category: kanto,
        correct_answer: 'Bulbasaur',
        incorrect_answers: ['Pikachu', 'Charmander', 'Squirtle'],
    },
    {
        id: 2,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre japonés de Jigglypuff?',
        category: kanto,
        correct_answer: 'Purin',
        incorrect_answers: ['Jigglytuff', 'Wigglytuff', 'Puffball'],
    },
    {
        id: 3,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del gimnasio de Ciudad Celeste?',
        category: kanto,
        correct_answer: 'Misty',
        incorrect_answers: ['Brock', 'Erika', 'Lt. Surge'],
    },
    {
        id: 4,
        difficulty: 'Moderado',
        question: '¿Qué tipo de Pokémon es Mewtwo?',
        category: kanto,
        correct_answer: 'Psíquico',
        incorrect_answers: ['Eléctrico', 'Lucha', 'Fuego'],
    },
    {
        id: 5,
        difficulty: 'Difícil',
        question: '¿Qué objeto se necesita para evolucionar a Eevee en Espeon durante el día?',
        category: kanto,
        correct_answer: 'Baya Zreza',
        incorrect_answers: ['Piedra Solar', 'Baya Zidra', 'Baya Meloc'],
    },
    {
        id: 6,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon legendarios es un trío que representa el tiempo?',
        category: kanto,
        correct_answer: 'Dialga',
        incorrect_answers: ['Palkia', 'Giratina', 'Arceus'],
    },
    {
        id: 7,
        difficulty: 'Fácil',
        question: '¿Cuál es el Pokémon inicial de tipo Agua en la región de Kanto?',
        category: kanto,
        correct_answer: 'Squirtle',
        incorrect_answers: ['Bulbasaur', 'Charmander', 'Piplup'],
    },
    {
        id: 8,
        difficulty: 'Moderado',
        question: '¿Cuál es el nombre del equipo criminal que se encuentra en Kanto?',
        category: kanto,
        correct_answer: 'Team Rocket',
        incorrect_answers: ['Team Magma', 'Team Aqua', 'Team Galactic'],
    },
    {
        id: 9,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del profesor Pokémon en la región de Kanto?',
        category: kanto,
        correct_answer: 'Profesor Oak',
        incorrect_answers: ['Profesor Elm', 'Profesor Birch', 'Profesor Kukui'],
    },
    {
        id: 10,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que vive en las Islas Espuma en Kanto?',
        category: kanto,
        correct_answer: 'Articuno',
        incorrect_answers: ['Zapdos', 'Moltres', 'Lugia'],
    },
	{
        id: 11,
        difficulty: 'Moderado',
        question: '¿Cuál es el nombre japonés de Magikarp?',
        category: kanto,
        correct_answer: 'Koiking',
        incorrect_answers: ['Splashy', 'Gyarados', 'Carpio'],
    },
    {
        id: 12,
        difficulty: 'Difícil',
        question: '¿Cuál es el tercer Pokémon que Brock captura en el anime?',
        category: kanto,
        correct_answer: 'Vulpix',
        incorrect_answers: ['Onix', 'Geodude', 'Zubat'],
    },
    {
        id: 13,
        difficulty: 'Fácil',
        question: '¿Cuál es el Pokémon que evoluciona de Eevee usando la Piedra Fuego?',
        category: kanto,
        correct_answer: 'Flareon',
        incorrect_answers: ['Jolteon', 'Vaporeon', 'Espeon'],
    },
    {
        id: 14,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Kanto?',
        category: kanto,
        correct_answer: 'Lorelei',
        incorrect_answers: ['Bruno', 'Agatha', 'Steven'],
    },
    {
        id: 15,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon se obtiene al intercambiar a Haunter?',
        category: kanto,
        correct_answer: 'Gengar',
        incorrect_answers: ['Gastly', 'Dusclops', 'Misdreavous'],
    },
    {
        id: 16,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon legendarios representa la creación?',
        category: kanto,
        correct_answer: 'Arceus',
        incorrect_answers: ['Dialga', 'Palkia', 'Giratina'],
    },
    {
        id: 17,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del equipo que Jesse y James pertenecen?',
        category: kanto,
        correct_answer: 'Team Rocket',
        incorrect_answers: ['Team Magma', 'Team Aqua', 'Team Galactic'],
    },
    {
        id: 18,
        difficulty: 'Moderado',
        question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon Rojo y Azul?',
        category: kanto,
        correct_answer: 'Blue',
        incorrect_answers: ['Red', 'Green', 'Ash'],
    },
    {
        id: 19,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del movimiento de Habilidad de Meowth?',
        category: kanto,
        correct_answer: 'Recoger',
        incorrect_answers: ['Corte', 'Zarpa', 'Gruñido'],
    },
    {
        id: 20,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que habita en la Cueva Celeste?',
        category: kanto,
        correct_answer: 'Mewtwo',
        incorrect_answers: ['Mew', 'Articuno', 'Zapdos'],
    },

	/* Preguntas de JOHTO 21-40 */

	{
        id: 21,
        difficulty: 'Fácil',
        question: '¿Cuál es el inicial de tipo Fuego en la región Johto?',
        category: johto,
        correct_answer: 'Cyndaquil',
        incorrect_answers: ['Totodile', 'Chikorita', 'Quilava'],
    },
    {
        id: 22,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del gimnasio de Ciudad Malva?',
        category: johto,
        correct_answer: 'Jasmine',
        incorrect_answers: ['Morty', 'Pryce', 'Whitney'],
    },
    {
        id: 23,
        difficulty: 'Difícil',
        question: '¿Qué objeto se necesita para evolucionar a Poliwhirl en Politoed?',
        category: johto,
        correct_answer: 'Roca del Rey',
        incorrect_answers: ['Piedra Agua', 'Piedra Dura', 'Roca Caliza'],
    },
    {
        id: 24,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre japonés de Sudowoodo?',
        category: johto,
        correct_answer: 'Usokki',
        incorrect_answers: ['Pseudotree', 'Woodo', 'Rockfake'],
    },
    {
        id: 25,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Johto?',
        category: johto,
        correct_answer: 'Karen',
        incorrect_answers: ['Will', 'Bruno', 'Lance'],
    },
    {
        id: 26,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Hada en la región Johto?',
        category: johto,
        correct_answer: 'Marill',
        incorrect_answers: ['Snubbull', 'Granbull', 'Azumarill'],
    },
    {
        id: 27,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Trigal?',
        category: johto,
        correct_answer: 'Falkner',
        incorrect_answers: ['Bugsy', 'Whitney', 'Morty'],
    },
    {
        id: 28,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Gloom en la región Johto?',
        category: johto,
        correct_answer: 'Bellossom',
        incorrect_answers: ['Vileplume', 'Roserade', 'Florges'],
    },
    {
        id: 29,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del equipo criminal que aparece en la región Johto?',
        category: johto,
        correct_answer: 'Team Rocket',
        incorrect_answers: ['Team Magma', 'Team Aqua', 'Team Galactic'],
    },
    {
        id: 30,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon que evoluciona de Togepi en la región Johto?',
        category: johto,
        correct_answer: 'Togetic',
        incorrect_answers: ['Togekiss', 'Togetank', 'Togetawd'],
    },
    {
        id: 31,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon legendarios habita en las Torres Latías y Latios en Johto?',
        category: johto,
        correct_answer: 'Latias',
        incorrect_answers: ['Latios', 'Ho-Oh', 'Lugia'],
    },
    {
        id: 32,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon Oro y Plata?',
        category: johto,
        correct_answer: 'Silver',
        incorrect_answers: ['Gold', 'Crystal', 'Ethan'],
    },
    {
        id: 33,
        difficulty: 'Moderado',
        question: '¿Cuál es el nombre del inicial de tipo Agua en la región Johto?',
        category: johto,
        correct_answer: 'Totodile',
        incorrect_answers: ['Chikorita', 'Cyndaquil', 'Feraligatr'],
    },
    {
        id: 34,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Sneasel en Weavile?',
        category: johto,
        correct_answer: 'Garra Afilada',
        incorrect_answers: ['Piedra Noche', 'Piedra Helada', 'Piedra Dura'],
    },
    {
        id: 35,
        difficulty: 'Fácil',
        question: '¿Cuál de estos Pokémon no es de tipo Eléctrico en Johto?',
        category: johto,
        correct_answer: 'Jolteon',
        incorrect_answers: ['Ampharos', 'Mareep', 'Raikou'],
    },
    {
        id: 36,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que habita en las Ruinas Alfa en Johto?',
        category: johto,
        correct_answer: 'Unown',
        incorrect_answers: ['Celebi', 'Ho-Oh', 'Lugia'],
    },
    {
        id: 37,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Psíquico en Johto?',
        category: johto,
        correct_answer: 'Espeon',
        incorrect_answers: ['Xatu', 'Slowking', 'Exeggutor'],
    },
    {
        id: 38,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Iris?',
        category: johto,
        correct_answer: 'Clair',
        incorrect_answers: ['Lance', 'Chuck', 'Jasmine'],
    },
    {
        id: 39,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Tyrogue en Johto?',
        category: johto,
        correct_answer: 'Hitmontop',
        incorrect_answers: ['Hitmonchan', 'Hitmonlee', 'Hitmonlee'],
    },
    {
        id: 40,
        difficulty: 'Difícil',
        question: '¿Cuál es el Pokémon que evoluciona de Porygon2 en la región Johto?',
        category: johto,
        correct_answer: 'Porygon-Z',
        incorrect_answers: ['Porygon-G', 'Porygon-W', 'Porygon-3'],
    },

	/* Preguntas HOENN */
	{
        id: 41,
        difficulty: 'Fácil',
        question: '¿Cuál es el inicial de tipo Planta en la región Hoenn?',
        category: hoenn,
        correct_answer: 'Treecko',
        incorrect_answers: ['Torchic', 'Mudkip', 'Grovyle'],
    },
    {
        id: 42,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del gimnasio de Ciudad Petalia?',
        category: hoenn,
        correct_answer: 'Winona',
        incorrect_answers: ['Norman', 'Brawly', 'Wattson'],
    },
    {
        id: 43,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Wurmple en Cascoon?',
        category: hoenn,
        correct_answer: 'Bicho Raro',
        incorrect_answers: ['Bicho Bola', 'Piedra Hoja', 'Piedra Dura'],
    },
    {
        id: 44,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre japonés de Skitty?',
        category: hoenn,
        correct_answer: 'Eneco',
        incorrect_answers: ['Cutiepuff', 'Meowpuff', 'Purrloin'],
    },
    {
        id: 45,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Hoenn?',
        category: hoenn,
        correct_answer: 'Drake',
        incorrect_answers: ['Sidney', 'Phoebe', 'Glacia'],
    },
    {
        id: 46,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Dragón en Hoenn?',
        category: hoenn,
        correct_answer: 'Altaria',
        incorrect_answers: ['Flygon', 'Salamence', 'Rayquaza'],
    },
    {
        id: 47,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Malvalona?',
        category: hoenn,
        correct_answer: 'Flannery',
        incorrect_answers: ['Roxanne', 'Brawly', 'Winona'],
    },
    {
        id: 48,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Ralts en la región Hoenn?',
        category: hoenn,
        correct_answer: 'Kirlia',
        incorrect_answers: ['Gardevoir', 'Gallade', 'Meditite'],
    },
    {
        id: 49,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del equipo criminal que aparece en la región Hoenn?',
        category: hoenn,
        correct_answer: 'Team Aqua / Team Magma',
        incorrect_answers: ['Team Rocket', 'Team Galactic', 'Team Plasma'],
    },
    {
        id: 50,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon que evoluciona de Lotad en la región Hoenn?',
        category: hoenn,
        correct_answer: 'Lombre',
        incorrect_answers: ['Ludicolo', 'Lomber', 'Ludico'],
    },
    {
        id: 51,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon legendarios habita en el Monte Pírico en Hoenn?',
        category: hoenn,
        correct_answer: 'Registeel',
        incorrect_answers: ['Regirock', 'Regice', 'Regigigas'],
    },
    {
        id: 52,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon Rubí y Zafiro?',
        category: hoenn,
        correct_answer: 'May / Brendan',
        incorrect_answers: ['Silver', 'Wally', 'Ethan / Lyra'],
    },
    {
        id: 53,
        difficulty: 'Moderado',
        question: '¿Cuál es el inicial de tipo Agua en la región Hoenn?',
        category: hoenn,
        correct_answer: 'Mudkip',
        incorrect_answers: ['Treecko', 'Torchic', 'Swampert'],
    },
    {
        id: 54,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Feebas en Milotic?',
        category: hoenn,
        correct_answer: 'Escala Bella',
        incorrect_answers: ['Piedra Lunar', 'Piedra Aqua', 'Piedra Pescado'],
    },
    {
        id: 55,
        difficulty: 'Fácil',
        question: '¿Cuál de estos Pokémon no es de tipo Planta en Hoenn?',
        category: hoenn,
        correct_answer: 'Breloom',
        incorrect_answers: ['Sceptile', 'Lombre', 'Roselia'],
    },
    {
        id: 56,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que habita en el Desierto del Raro en Hoenn?',
        category: hoenn,
        correct_answer: 'Regirock',
        incorrect_answers: ['Registeel', 'Regice', 'Golem'],
    },
    {
        id: 57,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Psíquico en Hoenn?',
        category: hoenn,
        correct_answer: 'Claydol',
        incorrect_answers: ['Gardevoir', 'Xatu', 'Medicham'],
    },
    {
        id: 58,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Colosalia?',
        category: hoenn,
        correct_answer: 'Norman',
        incorrect_answers: ['Winona', 'Roxanne', 'Brawly'],
    },
    {
        id: 59,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Nincada en Hoenn?',
        category: hoenn,
        correct_answer: 'Ninjask',
        incorrect_answers: ['Shedinja', 'Ninjafo', 'Ninshady'],
    },
    {
        id: 60,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon es la evolución de Vigoroth en la región Hoenn?',
        category: hoenn,
        correct_answer: 'Slaking',
        incorrect_answers: ['Slothking', 'Slacker', 'Slogre'],
    },

	/* Preguntas de SINNOH - 61-80 */
    {
        id: 61,
        difficulty: 'Fácil',
        question: '¿Cuál es el inicial de tipo Agua en la región Sinnoh?',
        category: sinnoh,
        correct_answer: 'Piplup',
        incorrect_answers: ['Turtwig', 'Chimchar', 'Prinplup'],
    },
    {
        id: 62,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del gimnasio de Ciudad Vetusta?',
        category: sinnoh,
        correct_answer: 'Roark',
        incorrect_answers: ['Fantina', 'Gardenia', 'Maylene'],
    },
    {
        id: 63,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Sneasel en Weavile?',
        category: sinnoh,
        correct_answer: 'Garra Afilada',
        incorrect_answers: ['Piedra Noche', 'Piedra Helada', 'Piedra Dura'],
    },
    {
        id: 64,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre japonés de Starly?',
        category: sinnoh,
        correct_answer: 'Mukkuru',
        incorrect_answers: ['Starbird', 'Starpidgey', 'Stareagle'],
    },
    {
        id: 65,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Sinnoh?',
        category: sinnoh,
        correct_answer: 'Cynthia',
        incorrect_answers: ['Lucian', 'Aaron', 'Bertha'],
    },
    {
        id: 66,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Dragón en Sinnoh?',
        category: sinnoh,
        correct_answer: 'Altaria',
        incorrect_answers: ['Garchomp', 'Dialga', 'Palkia'],
    },
    {
        id: 67,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Pirita?',
        category: sinnoh,
        correct_answer: 'Gardenia',
        incorrect_answers: ['Maylene', 'Fantina', 'Roark'],
    },
    {
        id: 68,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Budew en la región Sinnoh?',
        category: sinnoh,
        correct_answer: 'Roselia',
        incorrect_answers: ['Roserade', 'Rosesprout', 'Rosexie'],
    },
    {
        id: 69,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del equipo criminal que aparece en la región Sinnoh?',
        category: sinnoh,
        correct_answer: 'Team Galactic',
        incorrect_answers: ['Team Rocket', 'Team Plasma', 'Team Aqua / Team Magma'],
    },
    {
        id: 70,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon que evoluciona de Happiny en la región Sinnoh?',
        category: sinnoh,
        correct_answer: 'Chansey',
        incorrect_answers: ['Blissey', 'Chancy', 'Joyful'],
    },
    {
        id: 71,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon legendarios se cree que es el creador del universo en Sinnoh?',
        category: sinnoh,
        correct_answer: 'Arceus',
        incorrect_answers: ['Dialga', 'Palkia', 'Giratina'],
    },
    {
        id: 72,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon Diamante y Perla?',
        category: sinnoh,
        correct_answer: 'Barry',
        incorrect_answers: ['Pearl', 'Lucas', 'Diamond'],
    },
    {
        id: 73,
        difficulty: 'Moderado',
        question: '¿Cuál es el inicial de tipo Planta en la región Sinnoh?',
        category: sinnoh,
        correct_answer: 'Turtwig',
        incorrect_answers: ['Piplup', 'Chimchar', 'Grotle'],
    },
    {
        id: 74,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Magneton en Magnezone?',
        category: sinnoh,
        correct_answer: 'Piedra Dura',
        incorrect_answers: ['Piedra Solar', 'Piedra Noche', 'Piedra Helada'],
    },
    {
        id: 75,
        difficulty: 'Fácil',
        question: '¿Cuál de estos Pokémon no es de tipo Fuego en Sinnoh?',
        category: sinnoh,
        correct_answer: 'Infernape',
        incorrect_answers: ['Chimchar', 'Monferno', 'Magmortar'],
    },
    {
        id: 76,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que habita en el Lago Veraz en Sinnoh?',
        category: sinnoh,
        correct_answer: 'Uxie',
        incorrect_answers: ['Azelf', 'Mesprit', 'Dialga'],
    },
    {
        id: 77,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Siniestro en Sinnoh?',
        category: sinnoh,
        correct_answer: 'Spiritomb',
        incorrect_answers: ['Weavile', 'Honchkrow', 'Drapion'],
    },
    {
        id: 78,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Puntaneva?',
        category: sinnoh,
        correct_answer: 'Maylene',
        incorrect_answers: ['Crasher Wake', 'Byron', 'Roark'],
    },
    {
        id: 79,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Buizel en la región Sinnoh?',
        category: sinnoh,
        correct_answer: 'Floatzel',
        incorrect_answers: ['Floaty', 'Swimzel', 'Aqualog'],
    },
    {
        id: 80,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon es la evolución de Gligar en Gliscor en Sinnoh?',
        category: sinnoh,
        correct_answer: 'Piedra Noche',
        incorrect_answers: ['Piedra Dura', 'Piedra Solar', 'Piedra Helada'],
    },

	/* Preguntas acerca de TESELIA - 81-100  */
	{
        id: 81,
        difficulty: 'Fácil',
        question: '¿Cuál es el inicial de tipo Fuego en la región Teselia?',
        category: teselia,
        correct_answer: 'Tepig',
        incorrect_answers: ['Snivy', 'Oshawott', 'Pignite'],
    },
    {
        id: 82,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del gimnasio de Ciudad Gres?',
        category: teselia,
        correct_answer: 'Chili',
        incorrect_answers: ['Cress', 'Cilan', 'Lenora'],
    },
    {
        id: 83,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Pansear en Simisear?',
        category: teselia,
        correct_answer: 'Baya Tamate',
        incorrect_answers: ['Piedra Fuego', 'Piedra Calor', 'Piedra Dura'],
    },
    {
        id: 84,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre japonés de Lillipup?',
        category: teselia,
        correct_answer: 'Yorterrie',
        incorrect_answers: ['Lilpup', 'Puppyup', 'Lillette'],
    },
    {
        id: 85,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Teselia?',
        category: teselia,
        correct_answer: 'Alder',
        incorrect_answers: ['Shauntal', 'Grimsley', 'Caitlin'],
    },
    {
        id: 86,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Dragón en Teselia?',
        category: teselia,
        correct_answer: 'Reshiram',
        incorrect_answers: ['Haxorus', 'Druddigon', 'Zekrom'],
    },
    {
        id: 87,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Mayólica?',
        category: teselia,
        correct_answer: 'Lenora',
        incorrect_answers: ['Elesa', 'Clay', 'Burgh'],
    },
    {
        id: 88,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Pansage en la región Teselia?',
        category: teselia,
        correct_answer: 'Simisage',
        incorrect_answers: ['Sageape', 'Banape', 'Sagemonkey'],
    },
    {
        id: 89,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del equipo criminal que aparece en la región Teselia?',
        category: teselia,
        correct_answer: 'Team Plasma',
        incorrect_answers: ['Team Rocket', 'Team Galactic', 'Team Aqua / Team Magma'],
    },
    {
        id: 90,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon que evoluciona de Minccino en la región Teselia?',
        category: teselia,
        correct_answer: 'Cinccino',
        incorrect_answers: ['Minccinow', 'Furcoat', 'Peltchic'],
    },
    {
        id: 91,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon legendarios se cree que creó el mundo en Teselia?',
        category: teselia,
        correct_answer: 'Reshiram',
        incorrect_answers: ['Zekrom', 'Kyurem', 'Victini'],
    },
    {
        id: 92,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon Negro y Blanco?',
        category: teselia,
        correct_answer: 'Cheren',
        incorrect_answers: ['Bianca', 'Hugh', 'Hilbert / Hilda'],
    },
    {
        id: 93,
        difficulty: 'Moderado',
        question: '¿Cuál es el inicial de tipo Planta en la región Teselia?',
        category: teselia,
        correct_answer: 'Snivy',
        incorrect_answers: ['Tepig', 'Oshawott', 'Servine'],
    },
    {
        id: 94,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Panpour en Simipour?',
        category: teselia,
        correct_answer: 'Piedra Agua',
        incorrect_answers: ['Piedra Fresca', 'Piedra Mar', 'Piedra Calor'],
    },
    {
        id: 95,
        difficulty: 'Fácil',
        question: '¿Cuál de estos Pokémon no es de tipo Normal en Teselia?',
        category: teselia,
        correct_answer: 'Lilligant',
        incorrect_answers: ['Watchog', 'Pignite', 'Audino'],
    },
    {
        id: 96,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que habita en el Bosque Azulejo en Teselia?',
        category: teselia,
        correct_answer: 'Virizion',
        incorrect_answers: ['Terrakion', 'Cobalion', 'Keldeo'],
    },
    {
        id: 97,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Siniestro en Teselia?',
        category: teselia,
        correct_answer: 'Zorua',
        incorrect_answers: ['Liepard', 'Scrafty', 'Hydreigon'],
    },
    {
        id: 98,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Loza?',
        category: teselia,
        correct_answer: 'Elesa',
        incorrect_answers: ['Burgh', 'Clay', 'Skyla'],
    },
    {
        id: 99,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Minun en la región Teselia?',
        category: teselia,
        correct_answer: 'Minuslash',
        incorrect_answers: ['Pluslash', 'Electrolash', 'Minulash'],
    },
    {
        id: 100,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon es la evolución de Pidove en la región Teselia?',
        category: teselia,
        correct_answer: 'Tranquill',
        incorrect_answers: ['Calmite', 'Pidgeon', 'Peacebird'],
    },

	/* Preguntas acerca de TESELIA - 101-120  */
	{
		id: 101,
		difficulty: 'Fácil',
		question: '¿Cuál es el inicial de tipo Agua en la región Kalos?',
		category: kalos,
		correct_answer: 'Froakie',
		incorrect_answers: ['Chespin', 'Fennekin', 'Frogadier'],
	},
	{
		id: 102,
		difficulty: 'Moderado',
		question: '¿Cuál es el líder del gimnasio de Ciudad Novarte?',
		category: kalos,
		correct_answer: 'Grant',
		incorrect_answers: ['Valerie', 'Korrina', 'Clemont'],
	},
	{
		id: 103,
		difficulty: 'Difícil',
		question: '¿Cuál es el objeto necesario para evolucionar a Spritzee en Aromatisse?',
		category: kalos,
		correct_answer: 'Rosa Rocío',
		incorrect_answers: ['Piedra Belleza', 'Piedra Dulce', 'Piedra Dura'],
	},
	{
		id: 104,
		difficulty: 'Fácil',
		question: '¿Cuál es el nombre japonés de Bunnelby?',
		category: kalos,
		correct_answer: 'Horubee',
		incorrect_answers: ['Bunzoo', 'Digglet', 'Tunnelby'],
	},
	{
		id: 105,
		difficulty: 'Moderado',
		question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Kalos?',
		category: kalos,
		correct_answer: 'Diantha',
		incorrect_answers: ['Wikstrom', 'Siebold', 'Malva'],
	},
	{
		id: 106,
		difficulty: 'Difícil',
		question: '¿Cuál de estos Pokémon no es un tipo Dragón en Kalos?',
		category: kalos,
		correct_answer: 'Goodra',
		incorrect_answers: ['Dragalge', 'Noivern', 'Garchomp'],
	},
	{
		id: 107,
		difficulty: 'Fácil',
		question: '¿Cuál es el líder del gimnasio de Ciudad Luminalia?',
		category: kalos,
		correct_answer: 'Valerie',
		incorrect_answers: ['Olympia', 'Grant', 'Korrina'],
	},
	{
		id: 108,
		difficulty: 'Moderado',
		question: '¿Cuál de estos Pokémon es la evolución de Skiddo en la región Kalos?',
		category: kalos,
		correct_answer: 'Gogoat',
		incorrect_answers: ['Skidude', 'Goatee', 'Grassgoat'],
	},
	{
		id: 109,
		difficulty: 'Fácil',
		question: '¿Cuál es el nombre del equipo criminal que aparece en la región Kalos?',
		category: kalos,
		correct_answer: 'Team Flare',
		incorrect_answers: ['Team Rocket', 'Team Galactic', 'Team Plasma'],
	},
	{
		id: 110,
		difficulty: 'Moderado',
		question: '¿Cuál es el Pokémon que evoluciona de Spritzee en la región Kalos?',
		category: kalos,
		correct_answer: 'Aromatisse',
		incorrect_answers: ['Perfumette', 'Aromaquill', 'Scenton'],
	},
	{
		id: 111,
		difficulty: 'Difícil',
		question: '¿Cuál de estos Pokémon legendarios habita en la Torre Batalla en Kalos?',
		category: kalos,
		correct_answer: 'Zygarde',
		incorrect_answers: ['Xerneas', 'Yveltal', 'Diancie'],
	},
	{
		id: 112,
		difficulty: 'Fácil',
		question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon X e Y?',
		category: kalos,
		correct_answer: 'Tierno',
		incorrect_answers: ['Serena / Calem', 'Shauna', 'Trevor'],
	},
	{
		id: 113,
		difficulty: 'Moderado',
		question: '¿Cuál es el inicial de tipo Fuego en la región Kalos?',
		category: kalos,
		correct_answer: 'Fennekin',
		incorrect_answers: ['Froakie', 'Chespin', 'Delphox'],
	},
	{
		id: 114,
		difficulty: 'Difícil',
		question: '¿Cuál es el objeto necesario para evolucionar a Swirlix en Slurpuff?',
		category: kalos,
		correct_answer: 'Funda Dulce',
		incorrect_answers: ['Piedra Dulce', 'Piedra Helada', 'Piedra Luna'],
	},
	{
		id: 115,
		difficulty: 'Fácil',
		question: '¿Cuál de estos Pokémon no es de tipo Eléctrico en Kalos?',
		category: kalos,
		correct_answer: 'Gogoat',
		incorrect_answers: ['Heliolisk', 'Dedenne', 'Eelektross'],
	},
	{
		id: 116,
		difficulty: 'Moderado',
		question: '¿Cuál es el Pokémon legendario que habita en el Monte Ánima en Kalos?',
		category: kalos,
		correct_answer: 'Xerneas',
		incorrect_answers: ['Zygarde', 'Yveltal', 'Diancie'],
	},
	{
		id: 117,
		difficulty: 'Difícil',
		question: '¿Cuál de estos Pokémon no es un tipo Hada en Kalos?',
		category: kalos,
		correct_answer: 'Sylveon',
		incorrect_answers: ['Klefki', 'Florges', 'Dedenne'],
	},
	{
		id: 118,
		difficulty: 'Fácil',
		question: '¿Cuál es el líder del gimnasio de Ciudad Fresco?',
		category: kalos,
		correct_answer: 'Korrina',
		incorrect_answers: ['Ramos', 'Grant', 'Valerie'],
	},
	{
		id: 119,
		difficulty: 'Moderado',
		question: '¿Cuál de estos Pokémon es la evolución de Honedge en la región Kalos?',
		category: kalos,
		correct_answer: 'Doublade',
		incorrect_answers: ['Bladedge', 'Swordge', 'Armblade'],
	},
	{
		id: 120,
		difficulty: 'Difícil',
		question: '¿Cuál de estos Pokémon es la evolución de Tyrunt en la región Kalos?',
		category: kalos,
		correct_answer: 'Tyrantrum',
		incorrect_answers: ['Dinotrux', 'Tyranno', 'Kingdra'],
	},

	/* Preguntas acerca de ALOLA - 121-140 */
	{
        id: 121,
        difficulty: 'Fácil',
        question: '¿Cuál es el inicial de tipo Planta en la región Alola?',
        category: alola,
        correct_answer: 'Rowlet',
        incorrect_answers: ['Litten', 'Popplio', 'Dartrix'],
    },
    {
        id: 122,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del primer Pokémon Dojo en la región Alola?',
        category: alola,
        correct_answer: 'Mustard',
        incorrect_answers: ['Bea', 'Avery', 'Kahili'],
    },
    {
        id: 123,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Crabrawler en Crabominable?',
        category: alola,
        correct_answer: 'Subir Montaña',
        incorrect_answers: ['Piedra Fría', 'Piedra Dura', 'Piedra Agua'],
    },
    {
        id: 124,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre japonés de Pikipek?',
        category: alola,
        correct_answer: 'Tsutsukera',
        incorrect_answers: ['Pekachu', 'Peckaboo', 'Pekkie'],
    },
    {
        id: 125,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Alola?',
        category: alola,
        correct_answer: 'Kukui',
        incorrect_answers: ['Hala', 'Olivia', 'Acerola'],
    },
    {
        id: 126,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Siniestro en Alola?',
        category: alola,
        correct_answer: 'Decidueye',
        incorrect_answers: ['Incineroar', 'Inkay', 'Grimmsnarl'],
    },
    {
        id: 127,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Kantai?',
        category: alola,
        correct_answer: 'Acerola',
        incorrect_answers: ['Hala', 'Olivia', 'Kahuna'],
    },
    {
        id: 128,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Rockruff en la región Alola?',
        category: alola,
        correct_answer: 'Lycanroc',
        incorrect_answers: ['Rockhound', 'Stonepup', 'Roccanine'],
    },
    {
        id: 129,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del equipo criminal que aparece en la región Alola?',
        category: alola,
        correct_answer: 'Team Skull',
        incorrect_answers: ['Team Rocket', 'Team Galactic', 'Team Flare'],
    },
    {
        id: 130,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon que evoluciona de Cutiefly en la región Alola?',
        category: alola,
        correct_answer: 'Ribombee',
        incorrect_answers: ['Flitterby', 'Beecharm', 'Honeyfairy'],
    },
    {
        id: 131,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon legendarios es conocido como el "Renacuajo Solitario" en Alola?',
        category: alola,
        correct_answer: 'Tapu Koko',
        incorrect_answers: ['Solgaleo', 'Lunala', 'Cosmog'],
    },
    {
        id: 132,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon Sol y Luna?',
        category: alola,
        correct_answer: 'Hau',
        incorrect_answers: ['Gladion', 'Lillie', 'Elio / Selene'],
    },
    {
        id: 133,
        difficulty: 'Moderado',
        question: '¿Cuál es el inicial de tipo Fuego en la región Alola?',
        category: alola,
        correct_answer: 'Litten',
        incorrect_answers: ['Rowlet', 'Popplio', 'Incineroar'],
    },
    {
        id: 134,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Charjabug en Vikavolt?',
        category: alola,
        correct_answer: 'Cargapiedras',
        incorrect_answers: ['Piedra Brillante', 'Piedra Dura', 'Piedra Solar'],
    },
    {
        id: 135,
        difficulty: 'Fácil',
        question: '¿Cuál de estos Pokémon no es de tipo Hada en Alola?',
        category: alola,
        correct_answer: 'Incineroar',
        incorrect_answers: ['Primarina', 'Mimikyu', 'Tapu Lele'],
    },
    {
        id: 136,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que habita en el Monte Rubor en Alola?',
        category: alola,
        correct_answer: 'Solgaleo',
        incorrect_answers: ['Lunala', 'Necrozma', 'Magearna'],
    },
    {
        id: 137,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Psíquico en Alola?',
        category: alola,
        correct_answer: 'Lurantis',
        incorrect_answers: ['Oranguru', 'Gothitelle', 'Reuniclus'],
    },
    {
        id: 138,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Konikoni?',
        category: alola,
        correct_answer: 'Olivia',
        incorrect_answers: ['Hala', 'Acerola', 'Mina'],
    },
    {
        id: 139,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Wimpod en la región Alola?',
        category: alola,
        correct_answer: 'Golisopod',
        incorrect_answers: ['Wimpy', 'Swordclaw', 'Bugblade'],
    },
    {
        id: 140,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon es la evolución de Jangmo-o en la región Alola?',
        category: alola,
        correct_answer: 'Hakamo-o',
        incorrect_answers: ['Dragono', 'Drakegon', 'Dragonite'],
    },

	/* Preguntas acerca de GALAR - 141-160 */
	{
        id: 141,
        difficulty: 'Fácil',
        question: '¿Cuál es el inicial de tipo Agua en la región Galar?',
        category: galar,
        correct_answer: 'Sobble',
        incorrect_answers: ['Grookey', 'Scorbunny', 'Drizzile'],
    },
    {
        id: 142,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del primer gimnasio en la región Galar?',
        category: galar,
        correct_answer: 'Milo',
        incorrect_answers: ['Nessa', 'Kabu', 'Opal'],
    },
    {
        id: 143,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Galarian Yamask en Runerigus?',
        category: galar,
        correct_answer: 'Volver a la Vida',
        incorrect_answers: ['Piedra Sombría', 'Piedra Dura', 'Piedra Helada'],
    },
    {
        id: 144,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre japonés de Wooloo?',
        category: galar,
        correct_answer: 'Uru',
        incorrect_answers: ['Baaaba', 'Fluffee', 'Sheeple'],
    },
    {
        id: 145,
        difficulty: 'Moderado',
        question: '¿Cuál es el líder del Alto Mando en la Liga Pokémon de Galar?',
        category: galar,
        correct_answer: 'Leon',
        incorrect_answers: ['Nessa', 'Kabu', 'Milo'],
    },
    {
        id: 146,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Dragón en Galar?',
        category: galar,
        correct_answer: 'Corviknight',
        incorrect_answers: ['Dragapult', 'Dracovish', 'Duraludon'],
    },
    {
        id: 147,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Pistón?',
        category: galar,
        correct_answer: 'Nessa',
        incorrect_answers: ['Milo', 'Kabu', 'Bea'],
    },
    {
        id: 148,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Rookidee en la región Galar?',
        category: galar,
        correct_answer: 'Corvisquire',
        incorrect_answers: ['Rookietwo', 'Crowlette', 'Rookideux'],
    },
    {
        id: 149,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del equipo criminal que aparece en la región Galar?',
        category: galar,
        correct_answer: 'Team Yell',
        incorrect_answers: ['Team Rocket', 'Team Galactic', 'Team Skull'],
    },
    {
        id: 150,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Impidimp en la región Galar?',
        category: galar,
        correct_answer: 'Morgrem',
        incorrect_answers: ['Trickster', 'Grimmope', 'Mischieveil'],
    },
    {
        id: 151,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon legendarios es conocido como el "Caballero de la Espada" en Galar?',
        category: galar,
        correct_answer: 'Zacian',
        incorrect_answers: ['Zamazenta', 'Eternatus', 'Calyrex'],
    },
    {
        id: 152,
        difficulty: 'Fácil',
        question: '¿Cuál es el nombre del rival del jugador en los juegos Pokémon Espada y Escudo?',
        category: galar,
        correct_answer: 'Hop',
        incorrect_answers: ['Bede', 'Marnie', 'Magnolia'],
    },
    {
        id: 153,
        difficulty: 'Moderado',
        question: '¿Cuál es el inicial de tipo Fuego en la región Galar?',
        category: galar,
        correct_answer: 'Scorbunny',
        incorrect_answers: ['Grookey', 'Sobble', 'Raboot'],
    },
    {
        id: 154,
        difficulty: 'Difícil',
        question: '¿Cuál es el objeto necesario para evolucionar a Sinistea en Polteageist?',
        category: galar,
        correct_answer: 'Fragancia Eterna',
        incorrect_answers: ['Té de la Vida', 'Té de la Muerte', 'Piedra Calor'],
    },
    {
        id: 155,
        difficulty: 'Fácil',
        question: '¿Cuál de estos Pokémon no es de tipo Siniestro en Galar?',
        category: galar,
        correct_answer: 'Frosmoth',
        incorrect_answers: ['Thievul', 'Grimmsnarl', 'Morpeko'],
    },
    {
        id: 156,
        difficulty: 'Moderado',
        question: '¿Cuál es el Pokémon legendario que habita en la Torre Batalla en Galar?',
        category: galar,
        correct_answer: 'Eternatus',
        incorrect_answers: ['Zacian', 'Zamazenta', 'Calyrex'],
    },
    {
        id: 157,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon no es un tipo Psíquico en Galar?',
        category: galar,
        correct_answer: 'Toxtricity',
        incorrect_answers: ['Indeedee', 'Orbeetle', 'Hatterene'],
    },
    {
        id: 158,
        difficulty: 'Fácil',
        question: '¿Cuál es el líder del gimnasio de Ciudad Artejo?',
        category: galar,
        correct_answer: 'Opal',
        incorrect_answers: ['Milo', 'Nessa', 'Kabu'],
    },
    {
        id: 159,
        difficulty: 'Moderado',
        question: '¿Cuál de estos Pokémon es la evolución de Clobbopus en la región Galar?',
        category: galar,
        correct_answer: 'Grapploct',
        incorrect_answers: ['Squidupper', 'Punchtacle', 'Octopunch'],
    },
    {
        id: 160,
        difficulty: 'Difícil',
        question: '¿Cuál de estos Pokémon es la evolución de Hatenna en la región Galar?',
        category: galar,
        correct_answer: 'Hattrem',
        incorrect_answers: ['Hatentwo', 'Hatrick', 'Hatspell'],
    },
];
